[package]
name = "builder-localized"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
builder-command = { path = "../command" }

camino.workspace = true
fs-err.workspace = true
log = "0.4"
unic-langid.workspace = true
