[package]
name = "builder-fontforge"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
builder-command = { path = "../command" }

fs-err.workspace = true
camino.workspace = true
log.workspace = true
seahash.workspace = true
