[package]
name = "builder-sass"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
builder-command = { path = "../command" }

camino.workspace = true
fs-err.workspace = true
lightningcss.workspace = true
log.workspace = true
