[install.plugin]
install = "cargo_cmd_package_name"

[postbuild.web.aarch64-apple-darwin.custom.plugin.action1]
test = "lorem"
test2 = "ipsum"
test3 = "dolor"

[postbuild.web.aarch64-apple-darwin.custom.plugin.action2]
test = "lorem"
test2 = "ipsum"

[postbuild.web.aarch64-apple-darwin.custom.plugin.action3]
test = "lorem"
test2 = "ipsum"

[postbuild.web.i686-pc-windows-msvc.custom.plugin.action3]
test = "lorem"
test2 = "ipsum"

[install.clippy]
version = "1"
install = "cargo_cmd_package_name"
