[package]
name = "builder-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
builder-command = { path = "../command" }

base64.workspace = true
camino.workspace = true
fs-err.workspace = true
log.workspace = true
seahash.workspace = true
wasm-pack.workspace = true
